
#ifndef _cldi_head__setup_platform_PLATFORM_H
#define _cldi_head__setup_platform_PLATFORM_H 1

#ifdef __cplusplus
extern "C" {
#endif


typedef enum _CLDI_PLATFORM_T
{
	CLDI_PLATFORM_UNKNOWN   = 0,
	CLDI_PLATFORM_STDLIB    = CLDI_PLATFORM_UNKNOWN,
	CLDI_PLATFORM_C_LIBRARY = CLDI_PLATFORM_UNKNOWN,

	CLDI_PLATFORM_WINDOWS   = 1,
	CLDI_PLATFORM_MAC       = 2,
	CLDI_PLATFORM_LINUX     = 3,
	CLDI_PLATFORM_ANDROID   = 4,
	CLDI_PLATFORM_NETBSD    = 5,
	CLDI_PLATFORM_FREEBSD   = 5,
	CLDI_PLATFORM_OPENBSD   = 5,
	CLDI_PLATFORM_UNIX      = 6,
} CLDI_PLATFORM, CLDI_PLATFORM_T;

typedef enum _CLDI_ARCHSIZE_T
{
	CLDI_PLATFORM_32BIT = 32,
	CLDI_PLATFORM_64BIT = 64
} CLDI_ARCHSIZE, CLDI_ARCHSIZE_T;


#ifdef __cplusplus
}
#endif

#endif /* _cldi_head__setup_platform_PLATFORM_H */
